### PR TITLE
Create a deep clone of the payload before passing it to a users call back function

### PR DESCRIPTION
**Pull request by darcythomas**
### Changed

- The 'OnBeforeSend' and 'OnBeforeSendRUM' callbacks are now passed a clone of the payload, to prevent accidental pollution of global objects
- Updated the Github Action (Pre commit unit tests) Node to version 20

### CODE REVIEW

**Review by Olwiba — COMMENTED** [review]
Can you please add a description around why you want the change & also it looks like the package-lock was updated but I don't see any changes to the package.json - was there a mistake here?

**Comment by darcythomas** [comment]
> I don't see any changes to the package.json - was there a mistake here?

I did a npm update i think that did that

**Review by Olwiba — APPROVED** [review]
LGTM 👍

**Comment by darcythomas** [comment]
Ok presoaking now

**Pull request merged**
