### PR TITLE
Add partial matching for excluded hostnames.

### PR DESCRIPTION
**Pull request by ashclarke**
- Allows TLD filtering, such as internal staging TLDs.

### CODE REVIEW

**Comment by CmdrKeen** [comment]
I'm wondering if this might be better done through a wildcard support? What do you think Ash?

**Comment by ashclarke** [comment]
Sure, open to suggestions! I've got a couple of ideas, but just so I'm on the same track, do you have a specific way you wanted this done?

**Comment by CmdrKeen** [comment]
Sorry for the delay here Ash. I actually missed that it was a regex which means the end user would have as much flexibility as they wanted :-) 

We also have spec in there for tests, but there is only one. We should get more tests included in here.

I'll pass this PR over to @fundead who's the primary maintainer :+1:

**Comment by ashclarke** [comment]
Excellent, sounds good :)

**Pull request closed without merging**
